### ISSUE TITLE
Dynamic attach

### ISSUE THREAD

**Issue by planetlevel** [Contrast-Security-OSS/safelog4j#2]
So it can be added to a running app.

**Comment by JoeBeeton** [comment]
I'll take a look at that.

**Comment by planetlevel** [comment]
Erik created one.  Would be nice to do it in a ByteBuddy friendly way.

**Comment by JoeBeeton** [comment]
Hmm, just tested it and while it does attach to my sample application and I get the safelog4j message in my server log. I can still pop a calc.
running the app with the java agent does seem to block correctly. Will take a look.

**Comment by JoeBeeton** [comment]
Found a fix, there are a few issues that revolve around attaching, the way it works when running as an agent won't work when running against already loaded classes.  Will raise a PR tomorrow morning.

**Comment by planetlevel** [comment]
Rewrote interceptors to use Advice strategy to preserve class format and allow retransformation necessary for dynamic attach.  Also rewrote to use ByteBuddyAgent instead of pure instrumentation API.
